server:
  port: 8001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: migrations/db.changelog-master.yaml
    enabled: true

token:
  signing:
    key: ${JWT_SECRET}
  access:
    expiration: 15m
  refresh:
    expiration: 30d