server:
  port: 8002


spring:
  application:
    name: account-service
  liquibase:
    change-log: migrations/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}


token:
  signing:
    key: ${JWT_SECRET}
  access:
    ttl: 15m
  refresh:
    ttl: 30d